### PR TITLE
adds rails 5 beta3 support -> resolving dependencies

### PR DESCRIPTION
**Pull request by chilian**
All tests passing!

### CODE REVIEW

**Comment by dsandstrom** [comment]
Why the rspec-rails change?  Is it required for rails 5 gems?

**Comment by chilian** [comment]
Sorry, forgot to change this. I actually made a request to fix this.

**Comment by dsandstrom** [comment]
Tests don't pass after I merged this, not sure why yet.

**Comment by dsandstrom** [comment]
Fixed tests with #132

**Pull request merged**
