### PR TITLE
manually set dpl to edge

### PR DESCRIPTION
**Pull request by JoeWoodward**

### CODE REVIEW

**Comment by dgmstuart** [comment]
Wait, did that `add mime-types as a dependency` branch work?

**Comment by JoeWoodward** [comment]
@dgmstuart it did indeed but only when you set mime-types as a dependency in the gemspec. Which set's it to version < 3 for all ruby versions. Obviously not ideal.

**Comment by JoeWoodward** [comment]
@dgmstuart I have a funny feeling that we are experiencing a different issue to the dpl issue that travis-ci is experiencing. 

You can run bundle update locally to get the same issue

Another thing I've noticed is that we are experiencing this error in the install step of travis' build process. The referenced issue refers to the deploy step.

mime-types has updated and now does not support 1.9.3
While bundler is installing the dependencies it only looks for the latest version of mime-types that is compatible with the other gems in Gemfile, and does not check to see if that version of mime-types is compatible with the current version of ruby. 
We need to find a way to dynamically set the mime-types version in the Gemfile or set the mime-types version to the latest ruby-1.9.3-compatible version. 

It looks like mime-types is only used by capybara so wouldn't actually affect the general usage of foundation_rails_helper

**Comment by dgmstuart** [comment]
Oh - I misunderstood I thought mime-types was only a dependency of Travis itself :confused:

**Comment by JoeWoodward** [comment]
@dgmstuart That's what I thought at first too. It wasn't until I thought to try it locally that I realised that it wasn't just a travis error

**Comment by dgmstuart** [comment]
@JoeWoodward but wait, the issue is with `mime-types-data`, which is a different gem to the one I see in my Gemfile.lock (`mime-types`)

**Comment by JoeWoodward** [comment]
@dgmstuart mime-types-data is a dependency of mime-types I believe

**Comment by dgmstuart** [comment]
Huh - yes it looks like it: https://rubygems.org/gems/mime-types

But why doesn't it show up in my Gemfile.lock then?

**Comment by JoeWoodward** [comment]
That's very odd. It shows in mine

**Comment by dgmstuart** [comment]
Just checking: is this arguably a Capybara issue?

**Comment by JoeWoodward** [comment]
This is definitely an issue relating to Capybara if that's what you mean. 

You can delete `foundation_rails_helper.gemspec:26` (capybara dev_dependency) and the issue goes away. Obviously we can't do that because we would lose capybara from the local environment then.

**Comment by dgmstuart** [comment]
V. confused. Here's my gemfile on 1.9.3-p551 https://gist.github.com/dgmstuart/a85f8b1f9e9ddf0fa76f

It contains mime-types, but not mime-types data, and I don't have any issues bundling

**Comment by JoeWoodward** [comment]
Just checked, it appears mime-types-data is only a dependency for mime-types after version 3. 

You run `bundle update` not `bundle install` right?

**Comment by JoeWoodward** [comment]
https://gist.github.com/JoeWoodward/484a0b204eb2e1540083 there's my Gemfile.lock while bundling with ruby 2.2.2 (to prevent the incompatible ruby -v issue)

and with the mime-types -v < 3 https://gist.github.com/JoeWoodward/168819f38421699b5b4a

**Comment by dgmstuart** [comment]
Ah right -running bundle update pops it.

**Comment by JoeWoodward** [comment]
Yeah, while Gemfile.lock is present `bundle install` won't look for new versions of previously installed gems unless they've been changed in the Gemfile.

...unless you are installing for the first time. Hence why I found the error easier that you because it's a new repo on my machine so I had to bundle install to get the dependencies

**Comment by JoeWoodward** [comment]
I've created another PR btw

**Comment by dgmstuart** [comment]
So the options are 
1) drop support for 1.9 
2) restrict the version of capybara in the gemspec
3) restrict the version of mime-types in the gemspec

I'm actually in favour of 3) - I don't think that's a big deal at all since it's a dev dependency. But @dsandstrom (and maybe @sgruhier ?) should definitely comment.

Foundation 6 has just come out, and Rails 5 will be landing soon (and I think dropping support for 2.0 and below) so 1.9.3 will get dropped soon enough anyway.

**Comment by JoeWoodward** [comment]
I agree, option 3 seems most reasonable to me.

**Comment by dgmstuart** [comment]
Yup - I get that: I hadn't appreciated that this was due to a new version of mime-types being released.

**Comment by dsandstrom** [comment]
I'm for option 1.  I don't see a reason why we need to support Ruby 1.9.3 in the dev environment.  Locking mime-types in the gemspec seems like an easy enough fix, but that could just be the start and we might have to continue to juggle gem versions to keep support.  However, if you both agree on option 3, then we should move forward with that.

**Comment by dsandstrom** [comment]
Closing this in favor of #117

**Pull request closed without merging**
