### PR TITLE
Travis tests multiple rails versions

### PR DESCRIPTION
**Pull request by dgmstuart**
https://github.com/sgruhier/foundation_rails_helper/issues/136 highlights that it would be useful to be actively testing against all Rails versions that we're hoping to support. 

A blog post by Schneems gives a pattern for doing that: http://schneems.com/post/50991826838/testing-against-multiple-rails-versions/

### CODE REVIEW

**Comment by dgmstuart** [comment]
Problem 1: Rails 5 is only compatible with Ruby 2.2.0: http://logfile.swobspace.net/blog/2015/01/01/Ruby-and-Rails.html

**Comment by dgmstuart** [comment]
This is mostly working now. Outstanding issues:

1. Failing specs on Rails 5 - fixed by https://github.com/sgruhier/foundation_rails_helper/pull/137
2. Rails 4.1 and 4.2 failing with a "stack level too deep" in activesupport on Ruby 2.4.0-preview1 (Rails 5 and master are fine). This is probably totally unrelated to this gem. Options:

  a) Don't test against that Ruby yet
  b) `allow_failures` for that Ruby
  c) Only test Rails 5 and master against that Ruby

**Comment by dgmstuart** [comment]
@dsandstrom what do you reckon is the best option?

**Comment by dsandstrom** [comment]
It's looking more and more like the master branch should only support Foundation 6, Ruby 2.2+, and Rails 5.  In addition, we should have a branch that supports Foundation 5 / Rails 5 and a branch that supports Foundation 5 / Rails 4.  Although, we are already testing the limits in which we want to dedicate to upkeep.

**Comment by dgmstuart** [comment]
@dsandstrom that may be the right way to go, but I'm not sure it impacts what we decide to do regarding Ruby 2.4.0

I'm going to say we go with Option c - gives us some visibility of compatibility with the upcoming version, while not pointlessly running lots of builds on Travis

**Comment by dgmstuart** [comment]
OK, everything is now as it should be: only the Rails 5 builds are failing. 

@dsandstrom - would you mind reviewing and merging?
I've rebased and modified all the commits with reckless abandon.

**Comment by dsandstrom** [comment]
Sorry, didn't answer the 2.4 question, but I agree with you.

Haha, I've merged with reckless abandon :fingers_crossed:

**Pull request merged**
