### PR TITLE
Fix radio button generation

### PR DESCRIPTION
**Pull request by patricklindsay**
This fixes the radio button generation issue I referenced [here](https://github.com/sgruhier/foundation_rails_helper/issues/74).

### CODE REVIEW

**Comment by dsandstrom** [comment]
Thanks, I'll merge this tonight.

**Comment by dsandstrom** [comment]
I like the template approach, but I noticed the label can't be disabled.  I'll see if I can fix that.

**Comment by dsandstrom** [comment]
Also, the label should hide if options[:auto_labels] is false and a error message should show up below the input when there is an error on the field.

**Comment by dsandstrom** [comment]
Please submit a separate PR if you can.  Or I'll try to work on it more.

**Comment by patricklindsay** [comment]
I'll try take a look today.

**Comment by dsandstrom** [comment]
An error message doesn't make sense for radio buttons.  But, the
label_options should be passed to the label.

**Comment by patricklindsay** [comment]
Is the fix not to just use custom_label instead of label?
This handles adding the error class to the label and if text: false is passed in no label will appear.

**Comment by dsandstrom** [comment]
That should work.

**Pull request merged**
