### PR TITLE
Update flash_helper.rb

### PR DESCRIPTION
**Pull request by schopenhauer**
Updated key matchings with Foundation 5.2.2

### CODE REVIEW

**Comment by dgmstuart** [comment]
Hi @schopenhauer

Thanks for this, but there are a couple of issues: 

1. You need to update the tests when you make a change like this - they're currently failing. 
2. I don't quite understand your commit message - is there something special about that specific version?
3. You're suggesting that `notice` be changed from `success` (green) to `warning` (amber) - what's your rationale? I don't think this is correct: looking at the [Rails guides](http://guides.rubyonrails.org/action_controller_overview.html#the-flash) it looks like `:notice` is intended to be the default for 'non-alert' messages

**Comment by schopenhauer** [comment]
Hi @dgmstuart 

Just wanted to make sure the flash messages are linked to the correct classes in the most recent Foundation version (http://foundation.zurb.com/docs/components/alert_boxes.html) - i.e. success, warning, info, alert, secondary.

Could you please have a look and verify this?

Thanks a lot.

**Comment by dgmstuart** [comment]
@schopenhauer Ok cool, but my other points still stand: you need to update the tests accordingly, and `notice` should map to `success` not `warning`. Did you look at the rails guide I linked above?

Perhaps a new entry needs to be added for `warning`?

**Comment by dsandstrom** [comment]
The tests are failing because of the radio button helper is broken.  It only displays the label, the input is removed.  @patricklindsay has a fix for this (#74) and he mentioned he will submit a PR.

The flash helper tests use `FoundationRailsHelper::FlashHelper::DEFAULT_KEY_MATCHING.each` so whatever the current hash is will make the tests pass.

It was always odd to me that notice maps to success.  I think it should map to info or secondary, but not warning.  However, since users have been using info for success, it should probably not change.  However, this is a good case for the added configuration.  I will add a config hash that can be merged with the defaults.  And a way to add a radius or round class.

@schopenhauer I agree with @dgmstuart, please add a warning key/value, but don't change the notice value.

**Pull request merged**
