### PR TITLE
Travis builds mime-types gem before deploy

### PR DESCRIPTION
**Pull request by dgmstuart**
Travis has been raising issues related to the mime-types gem on ruby
1.9.3: https://github.com/sgruhier/foundation_rails_helper/issues/111

Fix was suggested here: http://stackoverflow.com/a/33856850/1035431

### CODE REVIEW

**Comment by dsandstrom** [comment]
Try this so it only affects 1.9.3:
```
before_deploy:
- rvm 1.9.3 do gem install mime-types -v 2.6.2
```

**Comment by dgmstuart** [comment]
@dsandstrom That also failed

**Comment by JoeWoodward** [comment]
Perhaps manually specifying the latest version of dpl may be a fix?

https://github.com/travis-ci/travis-ci/issues/5145#issuecomment-158678630
https://docs.travis-ci.com/user/deployment/#Adding-a-Provider

```
deploy:
  edge: true
rvm:
  - 1.9.3
  - 2.1.0
  - 2.2.0
```
or
```
deploy:
  edge:
    source: travis-ci/dpl
    branch: master
```

**Comment by dgmstuart** [comment]
@JoeWoodward good idea. Could you try making a new PR and see if you can get it to build?

**Pull request closed without merging**
