### PR TITLE
Don't output label="false" on radio_button

### PR DESCRIPTION
**Pull request by frenkel**
I noticed that setting label: false would generate label="false" as attribute on my radio buttons. This fixes it.

### CODE REVIEW

**Comment by dgmstuart** [comment]
Looks good to me. @dsandstrom ?

**Comment by dsandstrom** [comment]
Thanks for the PR and adding the test.  I'm not sure about naming the variable the same as the `label` method, seems like code smell.

**Comment by frenkel** [comment]
What would be a good name? The option is also called label. Calling it label_text seems wrong because it might also be false (meaning no label, not the text false).

**Comment by dsandstrom** [comment]
I'm alright with label_text.  Other possibilities are: label_value, label_option, temp_label.

**Comment by frenkel** [comment]
Ok. I've changed it.

**Comment by dsandstrom** [comment]
Thanks

**Pull request merged**
