### PR TITLE
Add rubocop

### PR DESCRIPTION
**Pull request by dsandstrom**
Lately, I've been using the [rubocop](https://github.com/bbatsov/rubocop) linter, which follows the [Ruby Style Guidline](https://github.com/bbatsov/ruby-style-guide).  I feel it keeps my code consistent and easy to read.  I purpose we add rubocop configs (*.rubocop.yml*) to this gem and enforce code style for future additions.  Also, I've added a linting step to our Travis CI so checking style is less painful.  Of course, the settings we choose for the rubocop configs are open to debate.

Where I deviate a little from the norm is I like to use double quotes in my spec files, while single everywhere else.

I'm willing to go through the code and fix any errors.

### CODE REVIEW

**Comment by andreslemik** [comment]
why not generate .rubocop_todo.yml?  or correct files listed in rubocop check report?

**Comment by dsandstrom** [comment]
I've never used the todo functionality, what is the benefit?

**Comment by dgmstuart** [comment]
@dsandstrom Two reasons: 

1. to exclude cases which rubocop flags up, but there are genuine reasons for not following a specific style rule.

2. To allow you to start off with a clean slate: start using rubocop straight away and highlight style issues with new code, while fixing style issues in older code in slow time.

**Comment by andreslemik** [comment]
@dsandstrom  rubocop --autogen-config - generate a configuration file acting as a TODO list.
rubocop -a - auto-correct certain offenses. Note: Experimental - use with caution.

**Comment by dgmstuart** [comment]
Closed in favour of #143

**Pull request closed without merging**
