### PR TITLE
Bumping rails gem versions

### PR DESCRIPTION
**Pull request by dgmstuart**

### CODE REVIEW

**Comment by dgmstuart** [comment]
@sgruhier @dsandstrom I'm pausing on merging this because previously https://github.com/sgruhier/foundation_rails_helper/commit/8550930da9720665b3bfea463f8e62ffdc0182ec bumped the gems to 4.2, and then https://github.com/sgruhier/foundation_rails_helper/commit/5b112b1a7df5b499012ce67a8af0046bf86812bc reverted that - what's the story behind that?

**Comment by dsandstrom** [comment]
@dgmstuart Sorry, that was me.  I got a little merge happy.  Is it causing problems?

**Comment by dgmstuart** [comment]
Not sure we're on the page: I'm asking if there's any reason not to do the version bump. It's probably fine, but I saw that you'd rolled back a previous version bump so I thought I'd better check.

**Comment by dsandstrom** [comment]
I bumped up the Rails version to 4.2 because I thought we should keep master at the latest Ruby/Rails.  However, the gem is compatible with Rails 4.1 with no extra effort.  So I went back to 4.1 in the gemspec.

What is the reason to force users to use Rails 4.1.10 and up?  The gem should work with Rails 4.1.1-4.1.10.

That being said, I'm not using Rails 4.1 in any projects so it is no big deal to me.

**Comment by dgmstuart** [comment]
Good point. I've been thinking about this backwards.

In that case, is there a specific reason to force 4.1.1 rather than 4.0.0+?
If not then the gemspec should simply be `'~> 4.1'` with no need for a  `>=`, right?

**Comment by dsandstrom** [comment]
I thought that there was a reason why we require Rails 4.1, but can't think of it.  If the tests pass for Rails 4.0, it should be fine.

**Comment by dgmstuart** [comment]
Cool - I've pushed that. Tests pass locally: we'll see what CI says

**Pull request merged**
