### PR TITLE
Foundation 6

### PR DESCRIPTION
**Pull request by chilian**
Updates to the new foundation 6 error classes add adds support for Rails5.0.0.beta3

### CODE REVIEW

**Comment by dsandstrom** [comment]
Thanks for the PR.  Can you point me to the docs that show these new CSS
classes?  It doesn't appear they change from what I've seen.

**Comment by chilian** [comment]
It seems like the form error state css stuff moved to a plugin called abide: http://foundation.zurb.com/sites/docs/abide.html
So I used these CSS classes which are working.
The "error" class doesn't work in my project (RoR5beta3, latest foundation-rails gem)

**Comment by dsandstrom** [comment]
This would make abide a requirement to use this gem.  I like abide and use it on many forms, but not all.  Also, I don't want to force it on everyone else.  Especially since currently abide isn't even apart of the gem.  I've wanted to add options to the form method to allow automatic abide error messages (See #100), but I haven't done any work on implementing this.

If we were going to change the error class, it would have to be done so by adding options to the form method or initializer.  The current error class works fine when not using abide, from my initial trials.

As for your case, it seems zurb has provided [options](http://foundation.zurb.com/sites/docs/abide.html#js-options) to change the error class that is used by abide.

I am open for discussion on this because I may be wrong or there are differing opinions.

@dgmstuart Whats your take?

**Comment by dgmstuart** [comment]
@dsandstrom I don't think this does introduce a dependency on abide (I agree that would be bad) - looks like the scss is in the main project: https://github.com/zurb/foundation-sites/blob/master/scss/forms/_error.scss

Also looks like this is the only place that field error styling is defined in v6. My guess is that the abide javascript toggles those specific classes, but we can also set them on the server side.

What I _am_ concerned about is the change to support Rails 5 - @chilian presumably that isn't required for the foundation upgrade to work? If not, then I feel like that should be a separate PR, since the discussion will be quite different.

**Comment by dsandstrom** [comment]
I reverted the gemspec, but merged the error class changes.

As @dgmstuart stated, the gemspec changes should be submitted in a different PR.  I think it would be smart to add an upper limit to the version numbers for the required gems.

**Pull request merged**
