### PR TITLE
Change input hint to help text

### LINKED ISSUE #145: Foundation 6 - Form input "hint" is now "help text"
http://foundation.zurb.com/sites/docs/forms.html#help-text

### PR DESCRIPTION
**Pull request by dsandstrom**
The text under the input has a different class so I changed the option
key and css class.

http://foundation.zurb.com/sites/docs/forms.html#help-text

Fixes #145

### CODE REVIEW

**Comment by dgmstuart** [comment]
@dsandstrom his needs a change in the readme, which still refers to 'hints'

**Comment by dsandstrom** [comment]
This has been fixed in #147

**Comment by dgmstuart** [comment]
OK

**Comment by dgmstuart** [comment]
@dsandstrom would you mind rebasing on top of foundation-6

**Comment by dsandstrom** [comment]
Closed in favor of #151

**Pull request closed without merging**
